error: Test unary error handling, remap ALREADY_EXISTS to 409
- Clear `details` field since JsonFormat can't serialize those.
- Remap ALREADY_EXISTS from 422 to 409